call C:\\Users\\David\\AppData\\Local\\Programs\\Python\\Python35\\python.exe %~dp0\..\tools\\python\\source\\generatevc.py %~dp0 %~dp0vs webengine -i .filters -i .sln -i .vcxproj -i .suo -i .sdf -i .db -i .log -c library_core -c library_core_render -c library_core_render_physics
set /p DUMMY=Hit ENTER to continue...
